/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: YNAB API Endpoints
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.youneedabudget.client.apis

import com.youneedabudget.client.models.ErrorResponse
import com.youneedabudget.client.models.PayeeResponse
import com.youneedabudget.client.models.PayeesResponse
import retrofit2.http.GET
import retrofit2.http.Headers

@JvmSuppressWildcards
interface PayeesApi {
    /**
     * Single payee
     * Returns single payee
     * The endpoint is owned by defaultname service owner
     * @param budgetId The id of the budget (\&quot;last-used\&quot; can be used to specify the last used budget and \&quot;default\&quot; can be used if default budget selection is enabled (see: https://api.youneedabudget.com/#oauth-default-budget) (required)
     * @param payeeId The id of the payee (required)
     */
    @Headers(
        "X-Operation-ID: getPayeeById"
    )
    @GET("budgets/{budget_id}/payees/{payee_id}")
    suspend fun getPayeeById(
        @retrofit2.http.Path("budget_id") budgetId: String,
        @retrofit2.http.Path("payee_id") payeeId: String
    ): PayeeResponse
    /**
     * List payees
     * Returns all payees
     * The endpoint is owned by defaultname service owner
     * @param budgetId The id of the budget (\&quot;last-used\&quot; can be used to specify the last used budget and \&quot;default\&quot; can be used if default budget selection is enabled (see: https://api.youneedabudget.com/#oauth-default-budget) (required)
     * @param lastKnowledgeOfServer The starting server knowledge.  If provided, only entities that have changed since `last_knowledge_of_server` will be included. (optional)
     */
    @Headers(
        "X-Operation-ID: getPayees"
    )
    @GET("budgets/{budget_id}/payees")
    suspend fun getPayees(
        @retrofit2.http.Path("budget_id") budgetId: String,
        @retrofit2.http.Query("last_knowledge_of_server") lastKnowledgeOfServer: Long?
    ): PayeesResponse
}
