/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: YNAB API Endpoints
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.youneedabudget.client.apis

import com.youneedabudget.client.models.ErrorResponse
import com.youneedabudget.client.models.PayeeLocationResponse
import com.youneedabudget.client.models.PayeeLocationsResponse
import retrofit2.http.GET
import retrofit2.http.Headers

@JvmSuppressWildcards
interface PayeeLocationsApi {
    /**
     * Single payee location
     * Returns a single payee location
     * The endpoint is owned by defaultname service owner
     * @param budgetId The id of the budget (\&quot;last-used\&quot; can be used to specify the last used budget and \&quot;default\&quot; can be used if default budget selection is enabled (see: https://api.youneedabudget.com/#oauth-default-budget) (required)
     * @param payeeLocationId id of payee location (required)
     */
    @Headers(
        "X-Operation-ID: getPayeeLocationById"
    )
    @GET("budgets/{budget_id}/payee_locations/{payee_location_id}")
    suspend fun getPayeeLocationById(
        @retrofit2.http.Path("budget_id") budgetId: String,
        @retrofit2.http.Path("payee_location_id") payeeLocationId: String
    ): PayeeLocationResponse
    /**
     * List payee locations
     * Returns all payee locations
     * The endpoint is owned by defaultname service owner
     * @param budgetId The id of the budget (\&quot;last-used\&quot; can be used to specify the last used budget and \&quot;default\&quot; can be used if default budget selection is enabled (see: https://api.youneedabudget.com/#oauth-default-budget) (required)
     */
    @Headers(
        "X-Operation-ID: getPayeeLocations"
    )
    @GET("budgets/{budget_id}/payee_locations")
    suspend fun getPayeeLocations(
        @retrofit2.http.Path("budget_id") budgetId: String
    ): PayeeLocationsResponse
    /**
     * List locations for a payee
     * Returns all payee locations for the specified payee
     * The endpoint is owned by defaultname service owner
     * @param budgetId The id of the budget (\&quot;last-used\&quot; can be used to specify the last used budget and \&quot;default\&quot; can be used if default budget selection is enabled (see: https://api.youneedabudget.com/#oauth-default-budget) (required)
     * @param payeeId id of payee (required)
     */
    @Headers(
        "X-Operation-ID: getPayeeLocationsByPayee"
    )
    @GET("budgets/{budget_id}/payees/{payee_id}/payee_locations")
    suspend fun getPayeeLocationsByPayee(
        @retrofit2.http.Path("budget_id") budgetId: String,
        @retrofit2.http.Path("payee_id") payeeId: String
    ): PayeeLocationsResponse
}
