/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: YNAB API Endpoints
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.ynab.client.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.util.UUID
import org.threeten.bp.ZonedDateTime

/**
 * @property id
 * @property name
 * @property type
 * @property onBudget Whether this account is on budget or not
 * @property closed Whether this account is closed or not
 * @property note
 * @property balance The current balance of the account in milliunits format
 * @property clearedBalance The current cleared balance of the account in milliunits format
 * @property unclearedBalance The current uncleared balance of the account in milliunits format
 * @property transferPayeeId The payee id which should be used when transferring to this account
 * @property directImportLinked Whether or not the account is linked to a financial institution for automatic transaction import.
 * @property directImportInError If an account linked to a financial institution (direct_import_linked&#x3D;true) and the linked connection is not in a healthy state, this will be true.
 * @property lastReconciledAt A date/time specifying when the account was last reconciled.
 * @property debtOriginalBalance The original debt/loan account balance, specified in milliunits format.
 * @property debtInterestRates The debt/loan account interest rate(s), by effective date.
 * @property debtMinimumPayments The minimum payment amount(s) for the debt/loan account, by effective date.  The amounts are specified in milliunits format.
 * @property debtEscrowAmounts The escrow value(s) for the debt/loan account, by effective date.  The amounts are specified in milliunits format.
 * @property deleted Whether or not the account has been deleted.  Deleted accounts will only be included in delta requests.
 */
@JsonClass(generateAdapter = true)
data class Account(
  @Json(name = "id") @field:Json(name = "id") var id: UUID,
  @Json(name = "name") @field:Json(name = "name") var name: String,
  @Json(name = "type") @field:Json(name = "type") var type: AccountType,
  @Json(name = "on_budget") @field:Json(name = "on_budget") var onBudget: Boolean,
  @Json(name = "closed") @field:Json(name = "closed") var closed: Boolean,
  @Json(name = "balance") @field:Json(name = "balance") var balance: Long,
  @Json(name = "cleared_balance") @field:Json(name = "cleared_balance") var clearedBalance: Long,
  @Json(name = "uncleared_balance") @field:Json(name = "uncleared_balance") var unclearedBalance:
    Long,
  @Json(name = "transfer_payee_id") @field:Json(name = "transfer_payee_id") var transferPayeeId:
    UUID,
  @Json(name = "deleted") @field:Json(name = "deleted") var deleted: Boolean,
  @Json(name = "note") @field:Json(name = "note") var note: String? = null,
  @Json(
    name = "direct_import_linked",
  ) @field:Json(name = "direct_import_linked") var directImportLinked: Boolean? = null,
  @Json(
    name = "direct_import_in_error",
  ) @field:Json(name = "direct_import_in_error") var directImportInError: Boolean? = null,
  @Json(
    name = "last_reconciled_at",
  ) @field:Json(name = "last_reconciled_at") var lastReconciledAt: ZonedDateTime? = null,
  @Json(
    name = "debt_original_balance",
  ) @field:Json(name = "debt_original_balance") var debtOriginalBalance: Long? = null,
  @Json(
    name = "debt_interest_rates",
  ) @field:Json(name = "debt_interest_rates") var debtInterestRates:
    LoanAccountPeriodicValue? = null,
  @Json(
    name = "debt_minimum_payments",
  ) @field:Json(name = "debt_minimum_payments") var debtMinimumPayments:
    LoanAccountPeriodicValue? = null,
  @Json(
    name = "debt_escrow_amounts",
  ) @field:Json(name = "debt_escrow_amounts") var debtEscrowAmounts:
    LoanAccountPeriodicValue? = null,
)
