/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: YNAB API Endpoints
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.ynab.client.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
* The type of account
* Values: CHECKING,SAVINGS,CASH,CREDITCARD,LINEOFCREDIT,OTHERASSET,OTHERLIABILITY,MORTGAGE,AUTOLOAN,STUDENTLOAN,PERSONALLOAN,MEDICALDEBT,OTHERDEBT
*/
@JsonClass(generateAdapter = false)
enum class AccountType(val value: String) {
    @Json(name = "checking") CHECKING("checking"),
    @Json(name = "savings") SAVINGS("savings"),
    @Json(name = "cash") CASH("cash"),
    @Json(name = "creditCard") CREDITCARD("creditCard"),
    @Json(name = "lineOfCredit") LINEOFCREDIT("lineOfCredit"),
    @Json(name = "otherAsset") OTHERASSET("otherAsset"),
    @Json(name = "otherLiability") OTHERLIABILITY("otherLiability"),
    @Json(name = "mortgage") MORTGAGE("mortgage"),
    @Json(name = "autoLoan") AUTOLOAN("autoLoan"),
    @Json(name = "studentLoan") STUDENTLOAN("studentLoan"),
    @Json(name = "personalLoan") PERSONALLOAN("personalLoan"),
    @Json(name = "medicalDebt") MEDICALDEBT("medicalDebt"),
    @Json(name = "otherDebt") OTHERDEBT("otherDebt")
}
