/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: YNAB API Endpoints
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.ynab.client.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import org.threeten.bp.LocalDate
import org.threeten.bp.ZonedDateTime
import java.util.UUID

/**
 * @property id
 * @property name
 * @property lastModifiedOn The last time any changes were made to the budget from either a web or mobile client
 * @property firstMonth The earliest budget month
 * @property lastMonth The latest budget month
 * @property dateFormat
 * @property currencyFormat
 * @property accounts The budget accounts (only included if `include_accounts&#x3D;true` specified as query parameter)
 */
@JsonClass(generateAdapter = true)
data class BudgetSummary(
    @Json(name = "id") @field:Json(name = "id") var id: UUID,
    @Json(name = "name") @field:Json(name = "name") var name: String,
    @Json(name = "last_modified_on") @field:Json(name = "last_modified_on") var lastModifiedOn: ZonedDateTime? = null,
    @Json(name = "first_month") @field:Json(name = "first_month") var firstMonth: LocalDate? = null,
    @Json(name = "last_month") @field:Json(name = "last_month") var lastMonth: LocalDate? = null,
    @Json(name = "date_format") @field:Json(name = "date_format") var dateFormat: DateFormat? = null,
    @Json(name = "currency_format") @field:Json(name = "currency_format") var currencyFormat: CurrencyFormat? = null,
    @Json(name = "accounts") @field:Json(name = "accounts") var accounts: List<Account>? = null
)
