/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: YNAB API Endpoints
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.ynab.client.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.util.UUID

/**
 * @property id
 * @property payeeId
 * @property latitude
 * @property longitude
 * @property deleted Whether or not the payee location has been deleted.  Deleted payee locations will only be included in delta requests.
 */
@JsonClass(generateAdapter = true)
data class PayeeLocation(
    @Json(name = "id") @field:Json(name = "id") var id: UUID,
    @Json(name = "payee_id") @field:Json(name = "payee_id") var payeeId: UUID,
    @Json(name = "latitude") @field:Json(name = "latitude") var latitude: String,
    @Json(name = "longitude") @field:Json(name = "longitude") var longitude: String,
    @Json(name = "deleted") @field:Json(name = "deleted") var deleted: Boolean
)
