/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: YNAB API Endpoints
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.ynab.client.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property transactionIds The transaction ids that were saved
 * @property transaction If a single transaction was specified, the transaction that was saved
 * @property transactions If multiple transactions were specified, the transactions that were saved
 * @property duplicateImportIds If multiple transactions were specified, a list of import_ids that were not created because of an existing `import_id` found on the same account
 * @property serverKnowledge The knowledge of the server
 */
@JsonClass(generateAdapter = true)
data class SaveTransactionsResponseData(
  @Json(name = "transaction_ids") @field:Json(name = "transaction_ids") var transactionIds:
    List<String>,
  @Json(name = "server_knowledge") @field:Json(name = "server_knowledge") var serverKnowledge: Long,
  @Json(name = "transaction") @field:Json(name = "transaction") var transaction:
    TransactionDetail? = null,
  @Json(name = "transactions") @field:Json(name = "transactions") var transactions:
    List<TransactionDetail>? = null,
  @Json(
    name = "duplicate_import_ids",
  ) @field:Json(name = "duplicate_import_ids") var duplicateImportIds: List<String>? = null,
)
