/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: YNAB API Endpoints
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.ynab.client.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.util.UUID
import org.threeten.bp.LocalDate

/**
 * @property id
 * @property dateFirst The first date for which the Scheduled Transaction was scheduled.
 * @property dateNext The next date for which the Scheduled Transaction is scheduled.
 * @property frequency
 * @property amount The scheduled transaction amount in milliunits format
 * @property memo
 * @property flagColor The scheduled transaction flag
 * @property accountId
 * @property payeeId
 * @property categoryId
 * @property transferAccountId If a transfer, the account_id which the scheduled transaction transfers to
 * @property deleted Whether or not the scheduled transaction has been deleted.  Deleted scheduled transactions will only be included in delta requests.
 * @property accountName
 * @property payeeName
 * @property categoryName The name of the category.  If a split scheduled transaction, this will be &#39;Split&#39;.
 * @property subtransactions If a split scheduled transaction, the subtransactions.
 */
@JsonClass(generateAdapter = true)
data class ScheduledTransactionDetail(
  @Json(name = "id") @field:Json(name = "id") var id: UUID,
  @Json(name = "date_first") @field:Json(name = "date_first") var dateFirst: LocalDate,
  @Json(name = "date_next") @field:Json(name = "date_next") var dateNext: LocalDate,
  @Json(name = "frequency") @field:Json(name = "frequency") var frequency:
    ScheduledTransactionDetail.FrequencyEnum,
  @Json(name = "amount") @field:Json(name = "amount") var amount: Long,
  @Json(name = "account_id") @field:Json(name = "account_id") var accountId: UUID,
  @Json(name = "deleted") @field:Json(name = "deleted") var deleted: Boolean,
  @Json(name = "account_name") @field:Json(name = "account_name") var accountName: String,
  @Json(name = "subtransactions") @field:Json(name = "subtransactions") var subtransactions:
    List<ScheduledSubTransaction>,
  @Json(name = "memo") @field:Json(name = "memo") var memo: String? = null,
  @Json(name = "flag_color") @field:Json(name = "flag_color") var flagColor:
    ScheduledTransactionDetail.FlagColorEnum? = null,
  @Json(name = "payee_id") @field:Json(name = "payee_id") var payeeId: UUID? = null,
  @Json(name = "category_id") @field:Json(name = "category_id") var categoryId: UUID? = null,
  @Json(
    name = "transfer_account_id",
  ) @field:Json(name = "transfer_account_id") var transferAccountId: UUID? = null,
  @Json(name = "payee_name") @field:Json(name = "payee_name") var payeeName: String? = null,
  @Json(
    name = "category_name",
  ) @field:Json(name = "category_name") var categoryName: String? = null,
) {
  /**
   * Values: NEVER, DAILY, WEEKLY, EVERYOTHERWEEK, TWICEAMONTH, EVERY4WEEKS, MONTHLY, EVERYOTHERMONTH, EVERY3MONTHS, EVERY4MONTHS, TWICEAYEAR, YEARLY, EVERYOTHERYEAR
   */
  @JsonClass(generateAdapter = false)
  enum class FrequencyEnum(
    val value: String,
  ) {
    @Json(name = "never")
    NEVER("never"),

    @Json(name = "daily")
    DAILY("daily"),

    @Json(name = "weekly")
    WEEKLY("weekly"),

    @Json(name = "everyOtherWeek")
    EVERYOTHERWEEK("everyOtherWeek"),

    @Json(name = "twiceAMonth")
    TWICEAMONTH("twiceAMonth"),

    @Json(name = "every4Weeks")
    EVERY4WEEKS("every4Weeks"),

    @Json(name = "monthly")
    MONTHLY("monthly"),

    @Json(name = "everyOtherMonth")
    EVERYOTHERMONTH("everyOtherMonth"),

    @Json(name = "every3Months")
    EVERY3MONTHS("every3Months"),

    @Json(name = "every4Months")
    EVERY4MONTHS("every4Months"),

    @Json(name = "twiceAYear")
    TWICEAYEAR("twiceAYear"),

    @Json(name = "yearly")
    YEARLY("yearly"),

    @Json(name = "everyOtherYear")
    EVERYOTHERYEAR("everyOtherYear"),
  }

  /**
   * The scheduled transaction flag
   * Values: RED, ORANGE, YELLOW, GREEN, BLUE, PURPLE
   */
  @JsonClass(generateAdapter = false)
  enum class FlagColorEnum(
    val value: String,
  ) {
    @Json(name = "red")
    RED("red"),

    @Json(name = "orange")
    ORANGE("orange"),

    @Json(name = "yellow")
    YELLOW("yellow"),

    @Json(name = "green")
    GREEN("green"),

    @Json(name = "blue")
    BLUE("blue"),

    @Json(name = "purple")
    PURPLE("purple"),

    @Json(name = "")
    NONE(""),
  }
}
