/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: YNAB API Endpoints
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.ynab.client.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.util.UUID

/**
 * @property id
 * @property transactionId
 * @property amount The subtransaction amount in milliunits format
 * @property memo
 * @property payeeId
 * @property payeeName
 * @property categoryId
 * @property categoryName
 * @property transferAccountId If a transfer, the account_id which the subtransaction transfers to
 * @property transferTransactionId If a transfer, the id of transaction on the other side of the transfer
 * @property deleted Whether or not the subtransaction has been deleted.  Deleted subtransactions will only be included in delta requests.
 */
@JsonClass(generateAdapter = true)
data class SubTransaction(
  @Json(name = "id") @field:Json(name = "id") var id: String,
  @Json(name = "transaction_id") @field:Json(name = "transaction_id") var transactionId: String,
  @Json(name = "amount") @field:Json(name = "amount") var amount: Long,
  @Json(name = "deleted") @field:Json(name = "deleted") var deleted: Boolean,
  @Json(name = "memo") @field:Json(name = "memo") var memo: String? = null,
  @Json(name = "payee_id") @field:Json(name = "payee_id") var payeeId: UUID? = null,
  @Json(name = "payee_name") @field:Json(name = "payee_name") var payeeName: String? = null,
  @Json(name = "category_id") @field:Json(name = "category_id") var categoryId: UUID? = null,
  @Json(
    name = "category_name",
  ) @field:Json(name = "category_name") var categoryName: String? = null,
  @Json(
    name = "transfer_account_id",
  ) @field:Json(name = "transfer_account_id") var transferAccountId: UUID? = null,
  @Json(
    name = "transfer_transaction_id",
  ) @field:Json(name = "transfer_transaction_id") var transferTransactionId: String? = null,
)
