/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: YNAB API Endpoints
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.ynab.client.apis

import com.ynab.client.models.UserResponse
import retrofit2.http.GET
import retrofit2.http.Headers

@JvmSuppressWildcards
interface UserApi {
  /**
   * User info
   * Returns authenticated user information
   * The endpoint is owned by defaultname service owner
   */
  @Headers(
    "X-Operation-ID: getUser",
  )
  @GET("user")
  suspend fun getUser(): UserResponse
}
