/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: YNAB API Endpoints
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.youneedabudget.client.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.util.UUID

/**
 * @property id
 * @property name
 * @property type The type of account. Note: payPal, merchantAccount, investmentAccount, and mortgage types have been deprecated and will be removed in the future.
 * @property onBudget Whether this account is on budget or not
 * @property closed Whether this account is closed or not
 * @property note
 * @property balance The current balance of the account in milliunits format
 * @property clearedBalance The current cleared balance of the account in milliunits format
 * @property unclearedBalance The current uncleared balance of the account in milliunits format
 * @property transferPayeeId The payee id which should be used when transferring to this account
 * @property deleted Whether or not the account has been deleted.  Deleted accounts will only be included in delta requests.
 */
@JsonClass(generateAdapter = true)
data class Account(
    @Json(name = "id") @field:Json(name = "id") var id: UUID,
    @Json(name = "name") @field:Json(name = "name") var name: String,
    @Json(name = "type") @field:Json(name = "type") var type: Account.TypeEnum,
    @Json(name = "on_budget") @field:Json(name = "on_budget") var onBudget: Boolean,
    @Json(name = "closed") @field:Json(name = "closed") var closed: Boolean,
    @Json(name = "balance") @field:Json(name = "balance") var balance: Long,
    @Json(name = "cleared_balance") @field:Json(name = "cleared_balance") var clearedBalance: Long,
    @Json(name = "uncleared_balance") @field:Json(name = "uncleared_balance") var unclearedBalance: Long,
    @Json(name = "transfer_payee_id") @field:Json(name = "transfer_payee_id") var transferPayeeId: UUID,
    @Json(name = "deleted") @field:Json(name = "deleted") var deleted: Boolean,
    @Json(name = "note") @field:Json(name = "note") var note: String? = null
) {
    /**
     * The type of account. Note: payPal, merchantAccount, investmentAccount, and mortgage types have been deprecated and will be removed in the future.
     * Values: CHECKING, SAVINGS, CASH, CREDITCARD, LINEOFCREDIT, OTHERASSET, OTHERLIABILITY, PAYPAL, MERCHANTACCOUNT, INVESTMENTACCOUNT, MORTGAGE
     */
    @JsonClass(generateAdapter = false)
    enum class TypeEnum(val value: String) {
        @Json(name = "checking") CHECKING("checking"),
        @Json(name = "savings") SAVINGS("savings"),
        @Json(name = "cash") CASH("cash"),
        @Json(name = "creditCard") CREDITCARD("creditCard"),
        @Json(name = "lineOfCredit") LINEOFCREDIT("lineOfCredit"),
        @Json(name = "otherAsset") OTHERASSET("otherAsset"),
        @Json(name = "otherLiability") OTHERLIABILITY("otherLiability"),
        @Json(name = "payPal") PAYPAL("payPal"),
        @Json(name = "merchantAccount") MERCHANTACCOUNT("merchantAccount"),
        @Json(name = "investmentAccount") INVESTMENTACCOUNT("investmentAccount"),
        @Json(name = "mortgage") MORTGAGE("mortgage")
    }
}
