/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: YNAB API Endpoints
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.youneedabudget.client.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property dateFormat
 * @property currencyFormat
 */
@JsonClass(generateAdapter = true)
data class BudgetSettings(
    @Json(name = "date_format") @field:Json(name = "date_format") var dateFormat: DateFormat,
    @Json(name = "currency_format") @field:Json(name = "currency_format") var currencyFormat: CurrencyFormat
)
