/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: YNAB API Endpoints
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.youneedabudget.client.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property budgets
 * @property defaultBudget The default budget, if the associated application is configured to support specifying it
 */
@JsonClass(generateAdapter = true)
data class BudgetSummaryResponseData(
    @Json(name = "budgets") @field:Json(name = "budgets") var budgets: List<BudgetSummary>,
    @Json(name = "default_budget") @field:Json(name = "default_budget") var defaultBudget: BudgetSummary? = null
)
