/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: YNAB API Endpoints
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.youneedabudget.client.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.util.UUID
import org.threeten.bp.LocalDate

/**
 * @property id
 * @property categoryGroupId
 * @property name
 * @property hidden Whether or not the category is hidden
 * @property originalCategoryGroupId If category is hidden this is the id of the category group it originally belonged to before it was hidden.
 * @property note
 * @property budgeted Budgeted amount in milliunits format
 * @property activity Activity amount in milliunits format
 * @property balance Balance in milliunits format
 * @property goalType The type of goal, if the category has a goal (TB&#x3D;&#39;Target Category Balance&#39;, TBD&#x3D;&#39;Target Category Balance by Date&#39;, MF&#x3D;&#39;Monthly Funding&#39;, NEED&#x3D;&#39;Plan Your Spending&#39;)
 * @property goalCreationMonth The month a goal was created
 * @property goalTarget The goal target amount in milliunits
 * @property goalTargetMonth The target month for the goal to be completed.  Only some goal types specify this date.
 * @property goalPercentageComplete The percentage completion of the goal
 * @property deleted Whether or not the category has been deleted.  Deleted categories will only be included in delta requests.
 */
@JsonClass(generateAdapter = true)
data class Category(
    @Json(name = "id") @field:Json(name = "id") var id: UUID,
    @Json(name = "category_group_id") @field:Json(name = "category_group_id") var categoryGroupId: UUID,
    @Json(name = "name") @field:Json(name = "name") var name: String,
    @Json(name = "hidden") @field:Json(name = "hidden") var hidden: Boolean,
    @Json(name = "budgeted") @field:Json(name = "budgeted") var budgeted: Long,
    @Json(name = "activity") @field:Json(name = "activity") var activity: Long,
    @Json(name = "balance") @field:Json(name = "balance") var balance: Long,
    @Json(name = "deleted") @field:Json(name = "deleted") var deleted: Boolean,
    @Json(name = "original_category_group_id") @field:Json(name = "original_category_group_id") var originalCategoryGroupId: UUID? = null,
    @Json(name = "note") @field:Json(name = "note") var note: String? = null,
    @Json(name = "goal_type") @field:Json(name = "goal_type") var goalType: Category.GoalTypeEnum? = null,
    @Json(name = "goal_creation_month") @field:Json(name = "goal_creation_month") var goalCreationMonth: LocalDate? = null,
    @Json(name = "goal_target") @field:Json(name = "goal_target") var goalTarget: Long? = null,
    @Json(name = "goal_target_month") @field:Json(name = "goal_target_month") var goalTargetMonth: LocalDate? = null,
    @Json(name = "goal_percentage_complete") @field:Json(name = "goal_percentage_complete") var goalPercentageComplete: Int? = null
) {
    /**
     * The type of goal, if the category has a goal (TB='Target Category Balance', TBD='Target Category Balance by Date', MF='Monthly Funding', NEED='Plan Your Spending')
     * Values: TB, TBD, MF, NEED
     */
    @JsonClass(generateAdapter = false)
    enum class GoalTypeEnum(val value: String) {
        @Json(name = "TB") TB("TB"),
        @Json(name = "TBD") TBD("TBD"),
        @Json(name = "MF") MF("MF"),
        @Json(name = "NEED") NEED("NEED")
    }
}
