/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: YNAB API Endpoints
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.youneedabudget.client.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The currency format setting for the budget.  In some cases the format will not be available and will be specified as null.
 * @property isoCode
 * @property exampleFormat
 * @property decimalDigits
 * @property decimalSeparator
 * @property symbolFirst
 * @property groupSeparator
 * @property currencySymbol
 * @property displaySymbol
 */
@JsonClass(generateAdapter = true)
data class CurrencyFormat(
    @Json(name = "iso_code") @field:Json(name = "iso_code") var isoCode: String,
    @Json(name = "example_format") @field:Json(name = "example_format") var exampleFormat: String,
    @Json(name = "decimal_digits") @field:Json(name = "decimal_digits") var decimalDigits: Int,
    @Json(name = "decimal_separator") @field:Json(name = "decimal_separator") var decimalSeparator: String,
    @Json(name = "symbol_first") @field:Json(name = "symbol_first") var symbolFirst: Boolean,
    @Json(name = "group_separator") @field:Json(name = "group_separator") var groupSeparator: String,
    @Json(name = "currency_symbol") @field:Json(name = "currency_symbol") var currencySymbol: String,
    @Json(name = "display_symbol") @field:Json(name = "display_symbol") var displaySymbol: Boolean
)
