/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: YNAB API Endpoints
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.youneedabudget.client.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The date format setting for the budget.  In some cases the format will not be available and will be specified as null.
 * @property format
 */
@JsonClass(generateAdapter = true)
data class DateFormat(
    @Json(name = "format") @field:Json(name = "format") var format: String
)
