/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: YNAB API Endpoints
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.youneedabudget.client.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property payees
 * @property serverKnowledge The knowledge of the server
 */
@JsonClass(generateAdapter = true)
data class PayeesResponseData(
    @Json(name = "payees") @field:Json(name = "payees") var payees: List<Payee>,
    @Json(name = "server_knowledge") @field:Json(name = "server_knowledge") var serverKnowledge: Long
)
