/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: YNAB API Endpoints
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.youneedabudget.client.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.util.UUID

/**
 * @property id
 * @property name
 * @property transferAccountId If a transfer payee, the `account_id` to which this payee transfers to
 * @property deleted Whether or not the payee has been deleted.  Deleted payees will only be included in delta requests.
 */
@JsonClass(generateAdapter = true)
data class Payee(
    @Json(name = "id") @field:Json(name = "id") var id: UUID,
    @Json(name = "name") @field:Json(name = "name") var name: String,
    @Json(name = "deleted") @field:Json(name = "deleted") var deleted: Boolean,
    @Json(name = "transfer_account_id") @field:Json(name = "transfer_account_id") var transferAccountId: String? = null
)
