/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: YNAB API Endpoints
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.youneedabudget.client.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property transaction
 * @property transactions
 */
@JsonClass(generateAdapter = true)
data class SaveTransactionsWrapper(
    @Json(name = "transaction") @field:Json(name = "transaction") var transaction: SaveTransaction? = null,
    @Json(name = "transactions") @field:Json(name = "transactions") var transactions: List<SaveTransaction>? = null
)
