/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: YNAB API Endpoints
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.youneedabudget.client.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.util.UUID

/**
 * @property id
 * @property scheduledTransactionId
 * @property amount The scheduled subtransaction amount in milliunits format
 * @property memo
 * @property payeeId
 * @property categoryId
 * @property transferAccountId If a transfer, the account_id which the scheduled subtransaction transfers to
 * @property deleted Whether or not the scheduled subtransaction has been deleted.  Deleted scheduled subtransactions will only be included in delta requests.
 */
@JsonClass(generateAdapter = true)
data class ScheduledSubTransaction(
    @Json(name = "id") @field:Json(name = "id") var id: UUID,
    @Json(name = "scheduled_transaction_id") @field:Json(name = "scheduled_transaction_id") var scheduledTransactionId: UUID,
    @Json(name = "amount") @field:Json(name = "amount") var amount: Long,
    @Json(name = "deleted") @field:Json(name = "deleted") var deleted: Boolean,
    @Json(name = "memo") @field:Json(name = "memo") var memo: String? = null,
    @Json(name = "payee_id") @field:Json(name = "payee_id") var payeeId: UUID? = null,
    @Json(name = "category_id") @field:Json(name = "category_id") var categoryId: UUID? = null,
    @Json(name = "transfer_account_id") @field:Json(name = "transfer_account_id") var transferAccountId: UUID? = null
)
