# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:      
    - uses: actions/checkout@v3.3.0
    - name: Set up our JDK environment
      uses: actions/setup-java@v3.10.0
      with:
        distribution: 'zulu'
        java-version: '11'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2.4.0
      with:
        arguments: build
