name: Tagged release

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 13
      uses: actions/setup-java@v2
      with:
        java-version: '13'
        distribution: 'zulu'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assemble

    - name: Automatic release
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        draft: true
        files: |
          LICENSE.txt
          build/distributions/*.tar
          build/distributions/*.zip
    
