name: Tagged release

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.7

      - name: Set up Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'zulu'
          java-version-file: .java-version
      - name: Set up gradle
        uses: gradle/actions/setup-gradle@v3.5.0
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.4.0
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and test with Gradle
        run: ./gradlew test installDist

      - name: Report test results
        uses: mikepenz/action-junit-report@v4.3.1
        if: success() || failure()
        with:
          report_paths: "**/build/test-results/test/*.xml"

      - name: Build, tag, and push docker image to Docker Hub
        uses: docker/build-push-action@v6.4.1
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ryanmoelter/splity:latest,ryanmoelter/splity:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Automatic release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          draft: true
          files: |
            LICENSE.txt
