name: Tagged release

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.7
    - name: Set up our JDK environment
      uses: actions/setup-java@v4.2.1
      with:
        distribution: 'zulu'
        java-version: '11'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v3.4.2
      with:
        arguments: assemble

    - name: Automatic release
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        draft: true
        files: |
          LICENSE.txt
          build/distributions/*.tar
          build/distributions/*.zip
    
